### PR TITLE
Corrected the log message.

### PR DESCRIPTION
**Pull request by umangachapagain**
tendrl-bug-id : Tendrl/commons/issues/990
Signed-off-by: Umanga Chapagain <chapagainumanga@gmail.com>

### CODE REVIEW

**Comment by umangachapagain** [comment]
@GowthamShanmugam @shtripat Please review my first PR

**Comment by anmolsachan** [comment]
LGTM

**Comment by GowthamShanmugam** [comment]
LGTM

**Comment by GowthamShanmugam** [comment]
LGTM

**Pull request closed without merging**
