### PR TITLE
Fix for authorize key module

### PR DESCRIPTION
**Pull request by GowthamShanmugam**
tendrl-bug-id: Tendrl/commons#274

Signed-off-by: GowthamShanmugam <gshanmug@redhat.com>

### CODE REVIEW

**Comment by GowthamShanmugam** [comment]
@r0h4n @shtripat @nnDarshan

**Comment by shtripat** [comment]
@GowthamShanmugam even after this PR merged, I see provisioner asking for confirmation while copying ssh key to other nodes.

**Comment by GowthamShanmugam** [comment]
@shtripat but i am setting environment variable for ansible in https://github.com/Tendrl/node-agent/blob/develop/tendrl-node-agent.service#L8

**Comment by GowthamShanmugam** [comment]
@shtripat then environment variable is in tendrl-node-agent.service, so if we run as a binary then it does not work, if we run as service then it will work fine.

**Comment by shtripat** [comment]
@GowthamShanmugam thanks. that was the issue. it works fine.

**Pull request merged**
