### PR TITLE
Fail node locking only if job is in progress in import flow

### PR DESCRIPTION
**Pull request by shtripat**
tendrl-bug-id: Tendrl/commons#860
Signed-off-by: Shubhendu <shtripat@redhat.com>

### CODE REVIEW

**Comment by shtripat** [comment]
DONT MERGE. NEED TO VERIFY.

**Comment by shtripat** [comment]
@GowthamShanmugam can we verify this in the setup you are having for expand flow testing?

**Comment by GowthamShanmugam** [comment]
we are releasing all nodes in finally block when any exception raised in import cluster atom https://github.com/Tendrl/commons/blob/master/tendrl/commons/objects/cluster/atoms/import_cluster/__init__.py#L175

why we need this change?

**Comment by GowthamShanmugam** [comment]
if we calling release lock from finally then we no need to worry about release lock

**Comment by shtripat** [comment]
If everything is happy path. still we should fail node locking only if parent job is in progress. If its failed/finished node locking should be allowed. @r0h4n comments?

**Comment by r0h4n** [comment]
I dont see the need to add this PR. Is it for some specific race condition between failure/finish and node lock release? @shtripat

**Comment by shtripat** [comment]
I remember I ran in this issue once where import job was failed and I immediately tried import again.

**Comment by r0h4n** [comment]
@shtripat  then you need to check why the nodes werent unlocked when the import job failed

**Comment by shtripat** [comment]
Abandoning at the moment. and would think later if we see this issue

**Pull request closed without merging**
