### PR TITLE
specify minimal required ansible version

### PR DESCRIPTION
**Pull request by dahorak**
- fixes Tendrl/commons/issues/1054

Signed-off-by: Daniel Horak <dahorak@redhat.com>

### CODE REVIEW

**Comment by dahorak** [comment]
run tests

**Comment by dahorak** [comment]
There might be some problem with the running ansible updating itself on the Tendrl server. I'll need to debug it slightly more deeply.

**Comment by dahorak** [comment]
This patch might cause update of ansible package on Tendrl Server, when ansible-playbook is running (with `site.yml`), which probably cause [following error](https://ci.centos.org/job/tendrl-2-1-cluster-gluster-install/594/console):
```
TASK [tendrl-ansible.tendrl-server : Configure etcd and graphite ip addr in node-agent.conf.yaml] ***
task path: /usr/share/ansible/roles/tendrl-ansible.tendrl-server/tasks/tendrl-node-agent.yml:12
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 96, in run
    try:
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 296, in _run_loop
    if loop_var in task_vars:
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 528, in _execute
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/normal.py", line 43, in run
    wrap_async = self._task.async_val and not self._connection.has_native_async
AttributeError: 'Task' object has no attribute 'async_val'

fatal: [n53.dusty.ci.centos.org]: FAILED! => {
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}
```

I'm not sure now, what is the best solution for this.

**Comment by anmolsachan** [comment]
@dahorak If we update the spec file of tendrl-ansible itself ( https://github.com/Tendrl/tendrl-ansible/blob/4acae343ad4fab4f16ce330e047403374d0cb7a6/tendrl-ansible.spec#L15 ) , Wouldn't it solve the issue ?

**Comment by dahorak** [comment]
As I wrote under [the related issue](https://github.com/Tendrl/commons/issues/1054#issuecomment-420205490), the main "problem" here is, that the expected *ansible* version (2.6) is in *epel* repository, which is added "automatically" when *tendrl-ansible*'s `site.yml` playbook is executed.
Based on the current documentation, when *tendrl-ansible* is installed, only the older version of *ansible* is available (from *CentOS-7 - Extras*). So we should also update the (pre)installation instructions to add *epel* repository manually before *tendrl-ansible* package is installed.

**Comment by mbukatov** [comment]
@anmolsachan  both tendrl-ansible and tendrl-commons requires ansible, so both should specify the minimal version. In upstream, one can try to use tendrl-ansible on another machine or install it from git repo, and in such case, minimal version in tendrl-commons will have it's effect.

**Comment by GowthamShanmugam** [comment]
@dahorak Need to specify the minimum version of ansible in setup.py also, otherwise it won't work when I do
python setup.py, install.

**Comment by GowthamShanmugam** [comment]
LGMT

**Comment by anmolsachan** [comment]
LGTM

**Comment by shtripat** [comment]
LGTM

**Comment by shtripat** [comment]
Fix the commit message, pep8 and squash in one commit.

**Pull request merged**
