### PR TITLE
Added a configuration for get version command for gluster

### PR DESCRIPTION
**Pull request by shtripat**
Signed-off-by: Shubhendu <shtripat@redhat.com>

### CODE REVIEW

**Comment by shtripat** [comment]
NEED TO VERIFY

**Comment by shtripat** [comment]
Wait till won't be a workable solution based on discussion on BZ. I will add the reference here.

**Comment by r0h4n** [comment]
Updates?

**Comment by shtripat** [comment]
@r0h4n I havent seen any updates on the BZ. @nthomas-redhat asked PM for confirmation.
@nthomas-redhat can you follow up on the same.

**Comment by shtripat** [comment]
Will be handled differently. Closing this.

**Pull request closed without merging**
