### PR TITLE
Logging changes according to new logging framework

### PR DESCRIPTION
**Pull request by anmolsachan**
tendrl-bug-id: Tendrl/specifications#28
tendrl-spec: Tendrl/specifications#127
reference-code-pr: Tendrl/commons#161

Signed-off-by: anmolsachan asachan@redhat.com

### CODE REVIEW

**Comment by r0h4n** [comment]
Can you please rebase this on top of develop branch

**Comment by anmolsachan** [comment]
@r0h4n Tendrl:spec-28-logging-coverage branch is tracking master I guess. Should I close this pr and send another pr against develop branch ?

**Comment by r0h4n** [comment]
Please rebase this on top of develop and update the PR

**Comment by anmolsachan** [comment]
@r0h4n I have rebased on top of develop

**Comment by r0h4n** [comment]
Please rebase this on top of develop

**Pull request merged**
