### PR TITLE
Packaging: Package build for el6

### PR DESCRIPTION
**Pull request by TimothyAsirJeyasing**
Signed-off-by: Timothy Asir J <tjeyasin@redhat.com>

### CODE REVIEW

**Comment by TimothyAsirJeyasing** [comment]
@r0h4n , @nthomas-redhat , @shtripat , please review

**Comment by sankarshanmukhopadhyay** [comment]
@TimothyAsir @Tendrl/tendrl-core - do note that el6/CentOS6 builds are lower in priority for the moment.

**Comment by r0h4n** [comment]
@TimothyAsirJeyasing Please update this PR

**Comment by r0h4n** [comment]
Closing this one, let me know once you resume working on this

**Pull request closed without merging**
