### PR TITLE
Added patch to remove ceph references for downstream only

### PR DESCRIPTION
**Pull request by shtripat**
Signed-off-by: Shubhendu <shtripat@redhat.com>

### CODE REVIEW

**Comment by shtripat** [comment]
@r0h4n @nthomas-redhat plz review

**Comment by nnDarshan** [comment]
@shtripat Should this be ds only change ? as we have already removed references to ceph in some places even in upstream.

**Comment by shtripat** [comment]
>> @shtripat Should this be ds only change ? as we have already removed references to ceph in 
>> some places even in upstream.

@nnDarshan yes I remember in import cluster flow all ceph references are removed now. @r0h4n what you feel? I am ok to delete this from upstream itself.

**Comment by r0h4n** [comment]
@shtripat Please remove it upstream

**Comment by shtripat** [comment]
>> @shtripat Please remove it upstream

Done. Will change it.

**Comment by shtripat** [comment]
@r0h4n plz check

**Pull request merged**
