### PR TITLE
Fix issue with plugin role interchange

### PR DESCRIPTION
**Pull request by anmolbabu**
tendrl-bug-id: Tendrl/commons#701
Signed-off-by: anmolbabu <anmolbudugutta@gmail.com>

### CODE REVIEW

**Comment by anmolbabu** [comment]
@r0h4n @nthomas-redhat @shtripat Please review

**Comment by anmolbabu** [comment]
Verified

**Comment by r0h4n** [comment]
File and link a issue for this

**Comment by anmolbabu** [comment]
@r0h4n Done

**Pull request merged**
