### PR TITLE
Added output field for job

### PR DESCRIPTION
**Pull request by shtripat**
If some job wants to update the output of the job inline
this field could be used.

Signed-off-by: Shubhendu <shtripat@redhat.com>

### CODE REVIEW

**Comment by shtripat** [comment]
This PR is sent to enable output population inline within job if some job wants to.

@brainfunked this would help saving calculated journal_mapping for ceph use case as suggested in https://github.com/Tendrl/node-agent/pull/371#pullrequestreview-33480058

**Comment by r0h4n** [comment]
Would this mean that all atoms inside a specific job can overwrite/append the Job.output field ?

**Comment by shtripat** [comment]
With this yes. Do you feel we should have output as dict with atom name as keys so that multiple atoms can write their output to the same field?

**Comment by r0h4n** [comment]
The API understands atoms run for a Job by its definitions. I would prefer a "JobOutput" object (takes job id as init param) which can be has attributes as atom names and value as the atom output, the flow can also add it output via its name in JobOutput object

**Pull request merged**
