### PR TITLE
Fixing an issue of geo-replication count not shown in grafana

### PR DESCRIPTION
**Pull request by GowthamShanmugam**
tendrl-bug-id: Tendrl/commons#1041
bugzilla: 1603175

Signed-off-by: GowthamShanmugasundaram <gshanmug@redhat.com>

### CODE REVIEW

**Comment by GowthamShanmugam** [comment]
@shtripat @r0h4n @nthomas-redhat please review

**Comment by GowthamShanmugam** [comment]
Verified with geo-replicaion-session

**Comment by GowthamShanmugam** [comment]
It has to be in any one place, but I can't remove this now. because i don't know what are all the places it is referred

**Comment by shtripat** [comment]
LGTM

**Comment by GowthamShanmugam** [comment]
@nthomas-redhat changes done

**Comment by nthomas-redhat** [comment]
@GowthamShanmugam , centos build failed(Timed out), pls resubmit

**Pull request merged**
