### PR TITLE
Flows and atoms for shrink cluster

### PR DESCRIPTION
**Pull request by GowthamShanmugam**
Signed-off-by: GowthamShanmugam <gshanmug@redhat.com>

### CODE REVIEW

**Comment by GowthamShanmugam** [comment]
@r0h4n @shtripat @nthomas-redhat @nnDarshan please review

**Comment by GowthamShanmugam** [comment]
this PR depends on https://github.com/Tendrl/node-agent/pull/542, https://github.com/Tendrl/python-gdeploy/pull/20

**Comment by r0h4n** [comment]
We are going to park this PR for a while, till I have more clarity

**Comment by GowthamShanmugam** [comment]
@r0h4n ok

**Pull request closed without merging**
