### PR TITLE
Definitions test

### PR DESCRIPTION
**Pull request by fbalak**
This is a work in progress. Do NOT merge.

Add test cases:
test_yaml_file_validity
test_definitions_node_agent_run_attributes

Results of test cases:
```
tendrl/node_agent/tests/test_definitions.py::test_yaml_file_validity PASSED
tendrl/node_agent/tests/test_definitions.py::test_definitions_node_agent_run_attributes[tendrl.node_agent.objects.Node.atoms.check_node_up] FAILED
tendrl/node_agent/tests/test_definitions.py::test_definitions_node_agent_run_attributes[tendrl.node_agent.atoms.service.validations.check_service_running] FAILED
tendrl/node_agent/tests/test_definitions.py::test_definitions_node_agent_run_attributes[tendrl.node_agent.atoms.node.cmd.Cmd] FAILED
tendrl/node_agent/tests/test_definitions.py::test_definitions_node_agent_run_attributes[tendrl.node_agent.atoms.package.validations.check_package_installed] FAILED
tendrl/node_agent/tests/test_definitions.py::test_definitions_node_agent_run_attributes[tendrl.node_agent.gluster_integration.objects.TendrlContext.atoms.check_cluster_id_exists] FAILED
tendrl/node_agent/tests/test_definitions.py::test_definitions_node_agent_run_attributes[tendrl.node_agent.gluster_integration.objects.Config.atoms.generate.Generate] FAILED
tendrl/node_agent/tests/test_definitions.py::test_definitions_node_agent_run_attributes[tendrl.node_agent.atoms.node.check_node_up] FAILED
tendrl/node_agent/tests/test_definitions.py::test_definitions_node_agent_run_attributes[tendrl.node_agent.objects.TendrlContext.atoms.compare] FAILED
```

Moved from https://github.com/Tendrl/node-agent/pull/283.

### CODE REVIEW

**Comment by r0h4n** [comment]
The source of the definitions in this PR is wrong, Please refer below pattern to find definition yamls for Tendrl namespaces

- https://github.com/Tendrl/commons/tree/develop/tendrl/commons/objects/definition -> (namespace.tendrl.objects.Definitions)

-- https://github.com/Tendrl/node-agent/tree/develop/tendrl/node_agent/objects/definition -> (namespace.node_agent.objects.Definitions)

-- https://github.com/Tendrl/node-agent/tree/develop/tendrl/provisioning/objects/definition -> (namespace.provisioning.objects.Definitions)

-- https://github.com/Tendrl/node-agent/tree/develop/tendrl/integrations/ceph/objects/definition -> (namespace.integrations.ceph.objects.Definitions)

-- https://github.com/Tendrl/node-agent/tree/develop/tendrl/integrations/gluster/objects/definition -> (namespace.integrations.gluster.objects.Definitions)

**Comment by r0h4n** [comment]
Any updates on this PR?

**Comment by r0h4n** [comment]
closing this one, please let me know if needs to be re-opened

**Comment by fbalak** [comment]
ok, I will re-visit this in future

**Comment by r0h4n** [comment]
Any updates?

**Comment by mbukatov** [comment]
While I consider this important, I can't guarantee when either @fbalak or myself will have enough time to recheck this. I will try to at least check the status next week.

**Pull request closed without merging**
