### PR TITLE
Unit Test Cases for Tendrl/commons

### PR DESCRIPTION
**Pull request by rishubhjain**
Unit test cases for tendrl/commons/

### CODE REVIEW

**Comment by r0h4n** [comment]
@rishubhjain the commit msg headline has to be meaningful, the "tendrl-bug-id: Tendrl/commons#180" can come a another line in the commit msg but not the first line, it doesnt make any sense

**Comment by rishubhjain** [comment]
@r0h4n Ya actually there was some mishap, I was trying to something else, will restructure it

**Comment by r0h4n** [comment]
@rishubhjain Current test coverage seems to be 81% https://travis-ci.org/Tendrl/commons/jobs/241752324

Will you be done covering 90% by today?

**Comment by rishubhjain** [comment]
@r0h4n yes I will be doing it today

**Pull request merged**
